name: GitHub Bump Example
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened, reopened]
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    if: startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
          sudo apt-get install libxml2-utils xmlstarlet
      - run: |
          chmod +x ./scripts/updateMinVersion.sh
      - run: |
          ./scripts/updateMinVersion.sh -path DotnetBump/DotnetBump/DotnetBump.csproj
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "bump version dependabot skip"
          git push
      
