name: GitHub Bump Example
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
          ./scripts/updateMinVersion.ps1 -path DotnetBump/DotnetBump/DotnetBump.csproj
        shell: pwsh
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "bump version dependabot skip"
          git push
      
