name: GitHub Bump Example
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
        currentVersion=$(xmlstarlet sel -t -v "Project/PropertyGroup/Version" DotnetBump/DotnetBump/DotnetBump.csproj)
        newVersion=$(echo $currentVersion | awk 'BEGIN{FS=OFS="."}{$NF++}1')
        xmlstarlet edit -L --update "Project/PropertyGroup/Version"  --value $newVersion DotnetBump/DotnetBump/DotnetBump.csproj
      - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "bump version dependabot skip"
        git push
      
